import { Header } from '@/shared/components/shared';

export const metadata = {
  title: 'NextJS',
  description: 'generated by JavaScript',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#f4f1ee]">
      <Header hasSearch={false} className="border-gray-200" />
      {children}
    </main>
  );
}
